print("Welcome to pegasus🔥")
#devloped by abhishekjha
print("Please enter to value ")
print("enter here")
inpunum=input()
print("table of\n",int(inpunum))
print(int(inpunum)*2)
print(int(inpunum)*3)
print(int(inpunum)*4)
print(int(inpunum)*5)
print(int(inpunum)*6)
print(int(inpunum)*7)
print(int(inpunum)*8)
print(int(inpunum)*9)
print(int(inpunum)*10)
